datasets:
  - name: Cd68Se55_650K
    xyz: path/to/run/QD.extxyz
    skip_frames: 500 #skip equilibrium frames
    first_n_frames: 2000

training:
  learning_rate: 0.02
  batch_size: 64
  convergence_patience: 40
  convergence_threshold: 0.0001
  validation_split: 0.15
  training_temperature: 650 #K
